apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
  labels:
    app: node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node
        image: akashacharya/test-build-nodejs:61118596f25b9866dbda36a8ad8472444eac56f0
        ports:
        - containerPort: 4000


