apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
  labels:
    app: node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node
        image: akashacharya/test-build-nodejs:${{ github.sha }}
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-12-07T08:04:22Z"
  labels:
    app: node
  name: deploy
  namespace: default
spec:
  ports:
  - port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    app: node
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
