apiVersion: v1
kind: Service
metadata:
  labels:
    app: node
  name: deploy
  namespace: default
spec:
  ports:
  - port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    app: node
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
